name: book_store
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Firebase
  cloud_firestore: ^3.4.7
  firebase_app_check: ^0.0.7+1
  firebase_auth: ^3.8.0
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.8
 
  #UI needs
  flutter_screenutil: ^5.5.4
  syncfusion_flutter_pdfviewer: ^20.3.59
  flutter_svg: ^1.1.5
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lottie: ^1.4.2
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  shimmer: ^2.0.0

  #Business logic needs
  json_serializable: ^6.3.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dio: ^4.0.6
  permission_handler: ^10.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  #File (storage) needs
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
